### ISSUE TITLE
Issue in updateDNS.yml for PTR record creation

### ISSUE THREAD

**Issue by fortinetps** [rutgerblom/vsphere-nsxt-lab-deploy#133]
First and foremost, thank you very much for your great works and sharing!

I ran into a small issue during the test of dev-v2 .

On playbook updateDNS.yml, there is missing zone value in nsupdate call, this would cause issue with error message, Failed to create DNS record

My temporary workaround is hardcoded the zone for IPv4/IPv6, e.g.
    - name: IPv4 'PTR' records for Nested_Router
      nsupdate:
        zone:     203.10.in-addr.arpa.
    - name: IPv6 'PTR' records for Nested_Router
      nsupdate:
        zone:     0.0.d.f.ipv6.arpa.

The DNS server is running with Ubuntu 20.04.1 Server and nsupdate version is 9.16.1

Thanks!
Don

**Comment by luischanu** [comment]
Hello Don,

I don't believe this is an issue for two reasons:

1) The NSUpdate documentation page indicates the following for the "Record" entry:
                    **_When zone is omitted this has to be absolute (ending with a dot)._**
So, as long as the "Record" entry is an absolute FQDN (i.e. Ending in a dot), zone isn't required, so this shouldn't be an issue.

2) The "ipaddr('revdns')" filter returns an absolute FQDN.  I just confirmed this by running the updateDNS.yml file with -vvv, and here is what the output of the "record" field showed for one of the records:
                    **_"record": "1.213.203.10.in-addr.arpa.",_**

Because the record value created is an absolute value, the inclusion of the zone field isn't required.

One additional side note.  When I was first creating the updateDNS.yml playbook, I included the "zone" field, but there were some other issues that arose around it, which using the absolute FQDN value resolved.

Sincerely,

Luis
