### ISSUE TITLE
BGP to external router instead of OSPF

### ISSUE THREAD

**Issue by howels** [rutgerblom/vsphere-nsxt-lab-deploy#143]
We're looking at this setup but we don't use OSPF. Can the VyOS router be configured to speak BGP to the external router via these templates?

**Comment by luischanu** [comment]
Hello @howels,

First, thank you for your input...

FYI, a design decision was made to use the OSPF (both v2 and v3) routing protocol in the the Lab-Routers network segment to simplify the deployment.  Because OSPF uses multicast to discover new neighbors, it allows new Pods to be brought on-line and discovered without any additional configuration.  When these new Pod's do come on-line, they immediately share routes with other Pods.  It also allows for a multi-pod environment if the user has a layer-3 switch that only supports static routes.  I hope that helps shed light why we chose to use OSPF over BGP.

BGP is definitely something that VyOS supports, so you could modify the VyOS template to configure the VyOS Pod-Router to use BGP in the Lab-Routers segment, but it's not something that we are planning on implementing as part of the project.  Or, you could just create the list of commands to enable the VyOS Pod-Router to communicate using BGP, and copy that in once the instance is up.  You could even automate that by simply creating an additional play at the end of the VyOS router playbook.

Thank you for your input, and we hope you enjoy the project.

Sincerely,

Luis

PS> FYI, we do have some optimizations planned for the VyOS structure, so the VyOS template will be changing in future releases.  I mention this only because if you do modify the VyOS Pod-Router template, keep track what you've added so you can roll those changes into the updated template in the future.

**Comment by howels** [comment]
Thanks. I will be discussing these options with the team in the near future. I hope that if we make BGP additions to the playbook we will be able to contribute them back for others to use.

**Comment by luischanu** [comment]
@howels, I did a little looking into VyOS Ansible support, and they have a module (vyos.vyos.vyos_config) that can send commands to the VyOS router.  No promises in delivering it, but if we have time (we have a lot of other things on our plate), after we're done with our other planned fixes/enhancements, I'll see if we can add a play near the end of the VyOS Router playbook that will take a text file that has VyOS commands in it, and then send those to the VyOS instance.   With this approach, the current configuration will be deployed and usable by most, but if you have any special commands that you want to add (like enabling BGP and disabling OSPF), you can just add those VyOS commands in the text file.  

I want to stress, this is NOT a commitment that this feature will be delivered, but more of a hope for the future, depending on our schedules.  So, until then, just work on developing your commands and paste those in manually...

**Comment by luischanu** [comment]
@howels, I just sent [THIS](https://twitter.com/LuisChanu/status/1379881094405705728) Tweet out today, and I think you might find it interesting.
