### ISSUE TITLE
Depoly Ubuntu VM Step for DNS VM fails

### ISSUE THREAD

**Issue by bunchc** [rutgerblom/vsphere-nsxt-lab-deploy#165]
Remote console of Ubuntu VM shows this:
![image](https://user-images.githubusercontent.com/2540442/114414064-212c6000-9b74-11eb-95a6-7a0cca9985fa.png)

The ansible step to show if the VM is active fails with this: https://gist.github.com/bunchc/749b01237128b3ca7edb8f129f7d5600

I am going to try to attach the console a bit earlier in the build to see what may be causing the crash.

**Comment by luischanu** [comment]
@bunchc , was this deployed from the v2 or dev-v3 branch?   I'm asking because I recently made some changes to the DNS server on the dev-v3 branch that I haven't had a chance to fully test yet, but will be doing so shortly.  So, if this was from the dev-v3 branch, I'd suggest you deploy the DNS server from the v2 branch.  Once I'm able to fully test the dev-v3 DNS, I'll update you.

**Comment by luischanu** [comment]
@bunchc I just finished performing a DNS server deployment using dev-v3 branch.  I did find one issue with the playbook (which I have corrected), but nothing related to your screenshot above.  What I found had to do with our internal debugging variables.  That said, once that debugging variable issue was corrected, the deployment of DNSServer completed successfully.   Please be aware that the DNSServer deployment does require Internet access, as it downloads modules during deployment from various repositories.

Here is the PLAY RECAP showing the test deployment of DNS Server (from dev-v3 branch):

![image](https://user-images.githubusercontent.com/16770181/114438292-681e5380-9b7c-11eb-8d76-dba9a80242da.png)

**Comment by bunchc** [comment]
Looks like that was it. I synced my fork and reran things and it built but then died as you suggested on the debug variable. I've synced again, and will give this another run shortly.
